### ISSUE TITLE
Can't install it on my computer

### ISSUE THREAD

**Issue by Dani-error** [peterprd/libpddokdo#13]
Well Im working at a Tweak that needs weather data, so I discovered this library.
I did the steps:
  > Clone the repo
  > Run ``make clean stage``
  > Install on my device
  > Add to my Tweak Header as ``<PeterDev/libpddokdo.h>``
  > Add to control, and Makefile depend

But when I build the tweak throws me this error:

> fatal error: 'PeterDev/libpddokdo.h' file not found
> #import <PeterDev/libpddokdo.h>

**Comment by Dani-error** [comment]
Don't worry, fixed!

**Comment by haxi0** [comment]
hello how did you fix it?
