### ISSUE TITLE
.DS_Store file accidentally left in the root of the deb file (as of version 1.3.1)

### ISSUE THREAD

**Issue by NintyTheRageKid** [peterprd/libpddokdo#8]
I don’t know why it’s there, and it’s clashing with an older (and somewhat no longer maintained) tweak I use that made the same mistake. Removing the file and pushing out a patch would be appreciated. Thank you.

**Comment by s8ngyu** [comment]
damn, I should've cleared it before the release. I'll push an update soon.

**Comment by s8ngyu** [comment]
23b6d05 fixes this issue
